sudo: required
services:
  - docker
os:
  - linux
env:
  global:
    - DOCKER_IMAGE_NAME="containerd"
    - DOCKER_HUB_ORG="daffa99"
before_install:
  - openssl aes-256-cbc -K $encrypted_6b4c930677fe_key -iv $encrypted_6b4c930677fe_iv -in deploy_rsa.enc -out deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 deploy_rsa
  - ssh-add deploy_rsa
  - docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
script:
  - sudo chmod +x deploy.sh
  - sudo chmod 600 deploy_rsa
after_script:
  - docker build -t ${DOCKER_HUB_ORG}/${DOCKER_IMAGE_NAME}:tukulsaBE-${TRAVIS_BUILD_ID} .
  - docker push ${DOCKER_HUB_ORG}/${DOCKER_IMAGE_NAME}:tukulsaBE-${TRAVIS_BUILD_ID}
  - docker tag ${DOCKER_HUB_ORG}/${DOCKER_IMAGE_NAME}:tukulsaBE-${TRAVIS_BUILD_ID} ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:BE2
  - docker push ${DOCKER_HUB_ORG}/${DOCKER_IMAGE_NAME}:BE2
  - ssh-keyscan -H $SSH_IP >> ~/.ssh/known_hosts
  - ssh -v -i deploy_rsa $SSH_USER@$SSH_IP DIR=$ROOT_DIR  'bash -s' < deploy.sh